version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    container_name: "laravel-php"
    working_dir: /src
    volumes:
      - ./src:/src
  mysql:
    image: mysql:5.7
    container_name: "laravel-mysql"
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: 好きなデータベース名
      MYSQL_ROOT_PASSWORD: root

  postgres:
    restart: always
    image: postgres:alpine
    container_name: "laravel-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 16379:6379
